### ISSUE TITLE
websearch functionality

### ISSUE THREAD

**Issue by Datenlord1510** [amir16yp/dailyreleases#1]
Is it essential to retain the Google-websearch functionality? This feature relies on Google's API (https://www.googleapis.com/customsearch/v1) and is also referenced in the configuration. If this functionality is not actively used, it may be better to consider its removal.

**Comment by amir16yp** [comment]
You're absolutely right. This feature doesn't even work when running on production even given the right parameters (API keys and such). I'll remove it after accepting the current pending pull request.
I'll make a separate issue about either rewriting or replacing it with something else (maybe bing or duckduckgo, whichever is more accurate and has an easy to access API)

**Comment by amir16yp** [comment]
removed in https://github.com/amir16yp/dailyreleases/commit/3c70f4999fe8219a0e99f6d9b4484d55c5fa4747
